### ISSUE TITLE
Can't seem to search

### ISSUE THREAD

**Issue by scgough** [prajjwaldimri/Genius.NET#14]
Hi,
I've just installed the package and I'm trying to carry out my first search.
I've registered my app on Genius and generated a token on there I want to use in the background of my website to grab lyrics and annotations. 

I try the following code below:

```
var geniusClient = new GeniusClient("MY_TOKEN_FROM_THE_GENIUS_PORTAL");
var lyricResult = await geniusClient.SearchClient.Search(Genius.Models.TextFormat.Dom, "1979 The Smashing Pumpkins");
```

and get the error:

`Object reference not set to an instance of an object.`

stack trace:
```
   at Genius.Http.ApiConnection.<Get>d__6`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Genius.Clients.SearchClient.<Search>d__2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyApp.Controllers.MyController.<TestAction>d__17.MoveNext() in ...
```

Can you help?

**Comment by scgough** [comment]
False alarm. Seems to just work now. It must have been an issue on genius’ side. 👍🏻
